### ISSUE TITLE
Cannot annotate without Login ? 

### ISSUE THREAD

**Issue by efisoft-elt** [elias-sundqvist/obsidian-annotator#188]
So I  have downloaded and installed it. 
If I try to annotate or highlights it ask me to log in or sign-up  (neither button work, I think because of popup) 

![image](https://user-images.githubusercontent.com/100837638/175964354-d8c651be-6a25-46d1-b9ed-3f43d0b71168.png)

Am I missing something ?  How can I annotate without loging to something ? 

Thanks.

**Comment by ljavuras** [comment]
Same problem here, this is a severe bug, all features of the plugin is inaccessible.
![image](https://user-images.githubusercontent.com/9023820/177230644-3b105d69-4e85-4ea3-8bf2-c6370ae08ff0.png)

**Comment by aberane** [comment]
Having the same issue, is there a workaround or fix yet?

**Comment by johnfuller** [comment]
It appears that some of the Hypothes.is resources being accessed by this plugin have changed locations. The first link shown below returns "access denied" when I try to access it directly. The second link works, and that's where the same files are being pulled from on a test of the parent service. My guess is that ideally these resources would be bundled with the plugin.

https://cdn.hypothes.is/hypothesis/1.1075.0/build/scripts/annotator.bundle.js

https://cdn.hypothes.is/hypothesis/build/scripts/annotator.bundle.js

**Comment by aladmit** [comment]
Hi everyone! All hypothesis files bundled into the plugin, including `annotator.bundle.js`. To fix this, we need to understand some people have issues with it, and some don't.

@efisoft-elt  @johnfuller @aberane @ljavuras Could you all please tell your obsidian version and obsidian installer version? I feel like some of these affect how plugin works, but I'm not sure which one and how.

**Comment by CedrikHarrich** [comment]
I have the same issue.
Obsidian Version: 0.15.6
Installer Version: 0.15.6

**Comment by SylvainGuieu** [comment]
Hi, 

Version 0.14.15
Installer V0.11.3

Then I have updated :
Version 0.15.16
Installer 0.11.3

Same problem

**Comment by avillani** [comment]
> Hi,
> 
> Version 0.14.15 Installer V0.11.3
> 
> Then I have updated : Version 0.15.16 Installer 0.11.3
> 
> Same problem.
> 
> ```
> > grep annotaotr.bundle main.js
> ..cdn.hypothes.is/hypothesis/build/scripts/annotator.bundle.js...
> ....cdn.hypothes.is/hypothesis/build/scripts/annotator.bundle.js.map....
> 
> ....cdn.hypothes.is/hypothesis/build/scripts/annotator.bundle.jsPK
> ....cdn.hypothes.is/hypothesis/build/scripts/annotator.bundle.js.mapPK....
> ```
> 
> And indeed this js script link is access denied for me.

I think what you need is to update the installer. https://github.com/elias-sundqvist/obsidian-annotator/issues/179#issuecomment-1153575147
It's working on my side with Version 0.15.6 ,Installer V0.14.15

**Comment by johnfuller** [comment]
@aladmit 

I just downloaded Obsidian-0.15.6-arm64.AppImage and I'm seeing the same issue. Note that it's ARM on Raspberry Pi.

PDFs work fine. I only have this issue with Epub files.

**Comment by SylvainGuieu** [comment]
I have updated the installer to v0.15.16 and it now works.

**Comment by johnfuller** [comment]
Update

It's working intermittently for me. I'll have to do more testing, but in one Epub, annotating may work in one chapter, but not another. I'm not sure this has anything to do with the errors I pointed out before. I'll do more testing and add anything I might find useful.

**Comment by ljavuras** [comment]
Updated my installer version to v0.15.6, and it works. My plugins and settings are all kept after re-installation.

Probably has something to do with the electron version, which comes with the installer, according to [this post](https://forum.obsidian.md/t/when-does-the-installer-version-matter/32367/2).

**Comment by aladmit** [comment]
@johnfuller Unfortunately, it's a known bug with epub :(

**Comment by aladmit** [comment]
That's interesting) A few people fixed the issue by updating installer version and one person have it with latest installer version 🤔 

I released a new version an hour ago. It's with a fix for iPad, but it affects how plugin fetches resources, so there is a change it fixes this problem too.

**Comment by johnfuller** [comment]
> That's interesting) A few people fixed the issue by updating installer version and one person have it with latest installer version 🤔 
> 
> I released a new version an hour ago. It's with a fix for iPad, but it affects how plugin fetches resources, so there is a change it fixes this problem too.

I'm betting the person who is still experiencing this with the latest is having this same problem as I am. I would call this resolved, as the issues I'm seeing are likely related to the parent, rather than the plugin. I think the simple fix for me is to stick to PDFs as much as possible. Thanks!
