### ISSUE TITLE
The plugin makes all the link fail to access with single click.

### ISSUE THREAD

**Issue by Anthony-Leo-368** [elias-sundqvist/obsidian-annotator#214]
The link of `show annotation` is fail to access to with just single left click. (still work if right click to open the sub menu and chose `open link`)

MORE OVER

All the link in file fail to jump with only single left click! That is a strange problem which idk whether u could recurrent in ur environment.

---

And there are the feed back in the console:

![Xnip2022-08-21_00-26-52](https://user-images.githubusercontent.com/68688891/185756892-75eb55e5-1dca-459c-a095-13b085a293c9.jpg)

---

Obsidian: v0.15.9
MacOS: 12.5.1
Annotator: 0.2.6

---

And here are all the plugin I installed:

![Xnip2022-08-21_00-29-48](https://user-images.githubusercontent.com/68688891/185757007-698373b4-09d2-4013-a883-6936ce3bce5c.jpg)

---

Best regard

**Comment by aladmit** [comment]
I thought we fixed this in 0.2.6 #208 😢 

Could you describe exactly what are you doing before you hit this problem? Step by step.

And I'm also interested in you obsidian **installer** version. Which version do you use? Have you tried to update it?

**Comment by Anthony-Leo-368** [comment]
I am glad to tell that after I try to reinstall  Annotator the issue for normal links are fixed.

^_^

---

But still the `show annotation` links still fail to jump (even I tried with right click and use `open link` button).
Here are the report in console when I opened a Annotated file, hope it may help.

![Xnip2022-08-21_11-39-17](https://user-images.githubusercontent.com/68688891/185774415-e526c7cb-3b7c-4403-8a78-ac4f7151894f.jpg)

---

And, the Installer version is `v0.15.8`

<img width="532" alt="image" src="https://user-images.githubusercontent.com/68688891/185774443-ffea2a13-af4c-473a-80fc-6f12135cb1f7.png">



---

**Comment by aladmit** [comment]
Yeah, looks like by fixing normal internal links in 0.2.6, I broke `show annotation` links 😞
