### ISSUE TITLE
Annotate button doesn't show at all

### ISSUE THREAD

**Issue by nhtquaan** [elias-sundqvist/obsidian-annotator#253]
Since I install Obsidian (1.0.3) and the Annotator plug-in, I've never seen the Annotate button showing up. Sometimes I can get into annotator mode if I add the code 
```
---
annotation-target: 1941 The rise of gentry - Land reform in UK.pdf
---
```
and then switch to the Reading view. But if I switch back to the Edit mode, I can no longer enter into annotator mode by switching to Reading mode again, similar to issue #247.

The problem persists whether option _Use annotation mode by Default_ in the Annotator plug-in options is ticked or not.

**Comment by aladmit** [comment]
Tested it today. Yep, I have the same behaviour 🤔

**Comment by paoloap-py** [comment]
same problem here

**Comment by HCarrott** [comment]
same for Obsidian (1.0.3)  on Mac.

**Comment by rews67** [comment]
I had the same issue, Annotate button doesn't show but when I press `ctrl + e` It goes into annotation.

**Comment by panoskyr** [comment]
Same issue. I cannot enter annotation mode with or without dataview enabled.

**Comment by peacefulwebwarrior** [comment]
Same :/

**Comment by elias-sundqvist** [comment]
Should be fixed in the new release

**Comment by nort4n** [comment]
The issue persists for me with epub files in version 0.2.8. No highlighting or annotating, no button showing up, when selecting text.

**Comment by voltaireodactyl** [comment]
I am also having this issue, solely with epubs as well.

**Comment by Kusou1** [comment]
same issue in mac , and then i set the command + e to toggle annotation/Markdown Mode,but not work

<img width="842" alt="image" src="https://user-images.githubusercontent.com/57334674/210575406-52ce3c2e-e2e1-4819-9a2e-db2d18595aae.png">

<img width="867" alt="image" src="https://user-images.githubusercontent.com/57334674/210575547-7c814f32-8141-431d-b7f8-0c6b5744887a.png">

then show me this error msg

**Comment by MickToews** [comment]
"This is still an issue for me using a Mac with Obsidian V 1.1.9 and Annotator 0.2.6.

While the annotate mode can open by default, there is no annotate button when in markdown mode to return to the annotate mode."

same issue here

**Comment by dfarkagallego** [comment]
Still an issue here

**Comment by dfarkagallego** [comment]
> same issue in mac , and then i set the command + e to toggle annotation/Markdown Mode,but not work
> 
> <img alt="image" width="842" src="https://user-images.githubusercontent.com/57334674/210575406-52ce3c2e-e2e1-4819-9a2e-db2d18595aae.png">
> 
> <img alt="image" width="867" src="https://user-images.githubusercontent.com/57334674/210575547-7c814f32-8141-431d-b7f8-0c6b5744887a.png">
> 
> then show me this error msg

Exactly the same message for me.

**Comment by dfarkagallego** [comment]
Not sure but it turn out that the preamble of one of my annotation notes had a wrong beggining, although when I started it worked and was on the fly that accidentaly change it. This seems to corrupt the whole pluggin that stop working in all annotations. When fixed this note Annotator start to work again. Fortunately this was one of my first annotations.

**Comment by payrim** [comment]
>"This is still an issue for me using a Mac with Obsidian V 1.1.9 and Annotator 0.2.6.

While the annotate mode can open by default, there is no annotate button when in markdown mode to return to the annotate mode.

same issue here "

also on linux for me
